export const GENRES = [
  { id: 1, genero: "Arte y Diseño", key: "arte_y_disenio" },
  { id: 2, genero: "Autoayuda y Desarrollo Personal", key: "autoayuda_y_desarrollo_personal" },
  { id: 3, genero: "Biografía/Autobiografía", key: "biografia_autobiografia" },
  { id: 4, genero: "Ciencia", key: "ciencia" },
  { id: 5, genero: "Ciencia Ficción", key: "ciencia_ficcion" },
  { id: 6, genero: "Ciencia y Naturaleza", key: "ciencia_y_naturaleza" },
  { id: 7, genero: "Crítica y Teoría Literaria", key: "critica_y_teoria_literaria" },
  { id: 8, genero: "Deporte y Aventura", key: "deporte_y_aventura" },
  { id: 9, genero: "Educativo y Didáctico", key: "educativo_y_didactico" },
  { id: 10, genero: "Ensayo", key: "ensayo" },
  { id: 11, genero: "Especializado", key: "especializado" },
  { id: 12, genero: "Estilo de Vida", key: "estilo_de_vida" },
  { id: 13, genero: "Ficción General", key: "ficcion_general" },
  { id: 14, genero: "Filosofía y Espiritualidad", key: "filosofia_y_espiritualidad" },
  { id: 15, genero: "Histórica", key: "historica" },
  { id: 16, genero: "Infantil/Juvenil", key: "infantil_juvenil" },
  { id: 17, genero: "Lingüística", key: "linguistica" },
  { id: 18, genero: "Lingüística y Estudios de Lengua", key: "linguistica_y_estudios_de_lengua" },
  { id: 19, genero: "Negocios y Economía", key: "negocios_y_economia" },
  { id: 20, genero: "Novela Gráfica y Cómic", key: "novela_grafica_y_comic" },
  { id: 21, genero: "Salud y Bienestar", key: "salud_y_bienestar" },
  { id: 22, genero: "Sociedad y Cultura", key: "sociedad_y_cultura" },
  { id: 23, genero: "Técnico y Científico", key: "tecnico_y_cientifico" },
  { id: 24, genero: "Thriller Legal", key: "thriller_legal" },
  { id: 25, genero: "Viajes y Geografía", key: "viajes_y_geografia" }
];
