export const GENRES = [
  { id: 1, genero: "Arte y Diseño" },
  { id: 2, genero: "Autoayuda y Desarrollo Personal" },
  { id: 3, genero: "Biografía/Autobiografía" },
  { id: 4, genero: "Ciencia" },
  { id: 5, genero: "Ciencia Ficción" },
  { id: 6, genero: "Ciencia y Naturaleza" },
  { id: 7, genero: "Crítica y Teoría Literaria" },
  { id: 8, genero: "Deporte y Aventura" },
  { id: 9, genero: "Educativo y Didáctico" },
  { id: 10, genero: "Ensayo" },
  { id: 11, genero: "Especializado" },
  { id: 12, genero: "Estilo de Vida" },
  { id: 13, genero: "Ficción General" },
  { id: 14, genero: "Filosofía y Espiritualidad" },
  { id: 15, genero: "Histórica" },
  { id: 16, genero: "Infantil/Juvenil" },
  { id: 17, genero: "Lingüística" },
  { id: 18, genero: "Lingüística y Estudios de Lengua" },
  { id: 19, genero: "Negocios y Economía" },
  { id: 20, genero: "Novela Gráfica y Cómic" },
  { id: 21, genero: "Salud y Bienestar" },
  { id: 22, genero: "Sociedad y Cultura" },
  { id: 23, genero: "Técnico y Científico" },
  { id: 24, genero: "Thriller Legal" },
  { id: 25, genero: "Viajes y Geografía" }
];
