export const LANGUAGES = [
    "Afgano", "Albanés", "Alemán", "Amhárico", "Árabe", "Armenio", "Azerbaiyano",
    "Bengalí", "Bielorruso", "Birmano", "Bosnio", "Búlgaro",
    "Catalán", "Cebuano", "Checo", "Chichewa", "Chino", "Coreano", "Corso", "Croata",
    "Danés", "Eslovaco", "Esloveno", "Español", "Esperanto", "Estonio",
    "Finés", "Francés", "Frisio",
    "Gallego", "Galés", "Georgiano", "Griego", "Gujarati",
    "Hausa", "Hawaiano", "Hebreo", "Hindi", "Hmong", "Holandés", "Húngaro",
    "Igbo", "Indonesio", "Inglés", "Irlandés", "Islandés", "Italiano",
    "Japonés", "Javanés",
    "Kazajo", "Khmer", "Kinyarwanda", "Kirguís", "Kurdo",
    "Lao", "Latín", "Letón", "Lituano", "Luxemburgués",
    "Macedonio", "Malayalam", "Malayo", "Malgache", "Maltés", "Maorí", "Maratí", "Mongol",
    "Nepalí", "Noruego",
    "Oriya", "Osetio",
    "Panyabí", "Pastún", "Persa", "Polaco", "Portugués",
    "Rumano", "Ruso",
    "Samoano", "Serbio", "Sesotho", "Shona", "Sindhi", "Singalés", "Somalí", "Suajili", "Sueco", "Sundanés",
    "Tagalo", "Tailandés", "Tamil", "Tártaro", "Telugu", "Turco", "Turcomano",
    "Ucraniano", "Uigur", "Urdu", "Uzbeco",
    "Vietnamita", "Xhosa", "Yidis", "Yoruba",
    "Zulú"
  ];