name: Create Pull Request Automatically

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automate pull request"
          title: "Automated Pull Request"
          body: "This pull request has been automatically created by GitHub Actions."
          branch: "auto-pr-${{ github.head_ref }}"
          delete-branch: true
          draft: false
